Introduce rc channel

diff --git a/bin/omarchy-refresh-pacman b/bin/omarchy-refresh-pacman
--- a/bin/omarchy-refresh-pacman
+++ b/bin/omarchy-refresh-pacman
@@ -33,10 +33,18 @@ Include = /etc/pacman.d/omarchy-mirrorlist
 EOF"
   fi
 
-else
-  sudo cp -f "$SRC_CONF" /etc/pacman.conf
+channel="${1:-stable}"
+
+if [[ "$channel" != "stable" && "$channel" != "rc" && "$channel" != "edge" ]]; then
+  echo "Error: Invalid channel '$channel'. Must be one of: stable, rc, edge"
+  exit 1
 fi
 
-sudo cp -f "$SRC_MIRROR" /etc/pacman.d/omarchy-mirrorlist
+echo "Setting channel to $channel"
+echo
 
+sudo cp -f "$OMARCHY_PATH/default/pacman/pacman-$channel.conf" /etc/pacman.conf
+sudo cp -f "$OMARCHY_PATH/default/pacman/mirrorlist-$channel" /etc/pacman.d/mirrorlist
+
+# Reset all package DBs and then update
 sudo pacman -Syyu --noconfirm
